### ISSUE TITLE
List of employees - Admin Dashboard

### ISSUE THREAD

**Issue by medinmujkovic** [medinmujkovic/QuickDine-RestaurantApp#5]
The admin dashboard needs to have:

- List of workers (employees who make the orders - Customer Service Dashboard)
- List of chefs (who accept a selected orders made by Customer Service Associates)

**Comment by abrulic1** [comment]
@medinmujkovic 
This should be divided in separate issues. 
     edit order-> separate issue
     delete user -> separate issue 
etc.
